#!python
def getCert(certHost='www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca',certfile=None,
            certQuery="/cred/proxyCert?daysValid=",daysValid=2):
    """Access the cadc certificate server"""

    import os

    if certfile is None:
	certfile=os.path.join(os.getenv("HOME","/tmp"),".ssl/cadcproxy.pem")

    dirname=os.path.dirname(certfile)
    try:
        os.makedirs(dirname)
    except OSError as e:
        if os.path.isdir(dirname):
            pass
        elif e.errno==20 or e.errno==17:
            import sys
            sys.stderr.write(e.strerror+": %s \n" %(dirname))
            sys.stderr.write("Expected %s to be a directory.\n" % ( dirname))
            sys.exit(e.errno)
        else:
            raise e
    
    import urllib2
    
    ## Example taken from voidspace.org.uk
    # create a password manager
    password_mgr = urllib2.HTTPPasswordMgrWithDefaultRealm()

    (username,passwd)=getUserPassword(host=certHost)

    # Add the username and password.
    # If we knew the realm, we could use it instead of ``None``.
    top_level_url = "http://"+certHost
    password_mgr.add_password(None, top_level_url, username, passwd)
    
    handler = urllib2.HTTPBasicAuthHandler(password_mgr)
    
    # create "opener" (OpenerDirector instance)
    opener = urllib2.build_opener(handler)
    
    # Install the opener.   
    urllib2.install_opener(opener)

    # Now all calls to urllib2.urlopen use our opener.
    url="http://"+certHost+certQuery+str(daysValid)
    r= urllib2.urlopen(url)
    w= file(certfile,'w')
    while True:
        buf=r.read()
        if not buf:
            break
        w.write(buf)
    w.close()
    r.close()
    return 

def getUserPassword(host='www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca'):
    import netrc,getpass,os,sys
    """"Getting the username/password for host from .netrc filie """
    if os.access(os.path.join(os.environ.get('HOME','/'),".netrc"),os.R_OK):
        auth=netrc.netrc().authenticators(host)
    else:
        auth=False
    if not auth:
        sys.stdout.write("CADC Username: ")
        username=sys.stdin.readline().strip('\n')
        password=getpass.getpass().strip('\n')
    else:
        username=auth[0]
        password=auth[2]
    return (username,password)


import optparse,os

parser = optparse.OptionParser(description='Get CADC proxy certificate')
parser.add_option('--daysValid', type=int, default=10,
                   help='Number of days the cetificate should be valid (default: 10)')
parser.add_option('--dest', default=os.path.join(os.getenv('HOME','/tmp'),".ssl/cadcproxy.pem"),
                    help="Location to store the proxy certifacte")
(opt,args) = parser.parse_args()

if __name__=='__main__':
    getCert(daysValid=opt.daysValid,certfile=opt.dest)
