/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_nrc_cadc_wcs_WCSLibTest */

#ifndef _Included_ca_nrc_cadc_wcs_WCSLibTest
#define _Included_ca_nrc_cadc_wcs_WCSLibTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_nrc_cadc_wcs_WCSLibTest
 * Method:    test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ca_nrc_cadc_wcs_WCSLibTest_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
