#!python
"""Create a directory (ContainerNode) in the VOSpace repositotry"""


import vos
import time
import optparse, os, sys, logging

usage="""
	vmkdir vos:/root/node   -- creates a new directory (ContainerNode) called node at vospace root 
"""


parser=optparse.OptionParser(usage)
parser.add_option("-v","--verbose",action="store_true")
parser.add_option("-d","--debug",action="store_true")
parser.add_option("--certfile",help="location of your CADC security certificate file",default=os.path.join(os.getenv("HOME","."),".ssl/cadcproxy.pem"))
parser.add_option("--overwrite",help="Overwrite the existing certificate with a new one?",action="store_true")

(opt,args)=parser.parse_args()


if opt.verbose:
    logging.basicConfig(level=logging.INFO,format="vmkdir: %(message)s")
if opt.debug:
    logging.basicConfig(level=logging.DEBUG,format="vcp:%(module)s.%(funcName)s %(message)s")


client=vos.Client(certFile=opt.certfile,overwrite=opt.overwrite)

for arg in args:
    if arg[0:4]!="vos:":
       logging.error("%s is not a valid VOSpace handle" % (arg))
    if client.isfile(arg):
       logging.info("deleting %s" %(arg))
       client.delete(arg)
    elif client.isdir(arg):
       logging.error("%s is a directory" % (arg))
    else:
       logging.error("%s file not found" % (arg))
