#!/usr/bin/env python2.7

"""vls:  list the contents of a voSpace"""
import logging
import math
import optparse
import os
import sys
import time
from vos import vos, __version__

usage = """
vls vos:VOSpaceTarget

lists information about the VOSpaceTarget, a data, link or container node. Requires read permission on vos:VOSpaceTarget

eg:  vls vos:jkavelaars

Version: %s """ % __version__.version


def get_terminal_size():
    """Get the size of the terminal

    @return: tuple(int, int) giving the row/column of the terminal screen.
    """

    def ioctl_gwinsz(fd):
        """

        @param fd: A file descriptor that points at the Screen Parameters
        @return: the termios screeen structure unpacked into an array.
        """
        try:
            import fcntl
            import termios
            import struct
            this_cr = struct.unpack('hh', fcntl.ioctl(fd, termios.TIOCGWINSZ, '1234'))
        except:
            return None
        return this_cr

    cr = ioctl_gwinsz(0) or ioctl_gwinsz(1) or ioctl_gwinsz(2)

    if not cr:
        try:
            td = os.open(os.ctermid(), os.O_RDONLY)
            cr = ioctl_gwinsz(td)
            td.close()
        except:
            pass
    if not cr:
        try:
            cr = (os.environ['LINES'], os.environ['COLUMNS'])
        except:
            cr = (25, 80)
    return int(cr[1]), int(cr[0])

parser = optparse.OptionParser(usage, add_help_option=False)
parser.add_option("--help", action="store_true")
parser.add_option("-l", "--long", action="store_true", help="verbose listing sorted by name")
parser.add_option("-g", "--group", action="store_true", help="display group read/write information")
parser.add_option("-h", "--human", action="store_true", help="make sizes human readable", default=False)
parser.add_option("-S", "--Size", action="store_true", help="sort files by size", default=False)
parser.add_option("-r", "--reverse", action="store_true", help="reverse the sort order", default=False)
parser.add_option("-t", "--time", action="store_true", help="sort by time copied to VOSpace")
parser.add_option("-v", "--verbose", action="store_true", help="print some diagnostics")
parser.add_option("-d", "--debug", action="store_true", help="print all diagnositics")
parser.add_option("-w", "--warning", action="store_true")
parser.add_option("--certfile",
                  help="location of your CADC security certificate file",
                  default=os.path.join(os.getenv("HOME", "."), ".ssl/cadcproxy.pem"))
parser.add_option("--overwrite",
                  help="Overwrite the existing certificate with a new one?",
                  action="store_true")
parser.add_option("--version", action="store_true", help="VOS Version %s" % __version__.version)

if len(sys.argv) == 1:
    parser.print_help()
    sys.exit()

(opt, args) = parser.parse_args()


if opt.version:
    sys.stdout.write("vls version %s \n\n" % __version__.version)
    sys.exit()
if opt.help:
    parser.print_help()
    sys.exit(0)

sortKey = False
if opt.time:
    sortKey = "date"
if opt.Size:
    sortKey = "size"


fmt = "%(message)s"
if opt.verbose:
    log_level = logging.INFO
elif opt.debug:
    log_level = logging.DEBUG
    fmt = "%(asctime)s - %(module)s.%(funcName)s %(lineno)d: %(message)s"

elif opt.warning:
    log_level = logging.WARNING
else:
    log_level = logging.ERROR

logger = logging.getLogger('vos')
logger.setLevel(log_level)
SH = logging.StreamHandler()
SH.setFormatter(logging.Formatter(fmt=fmt))
logger.addHandler(SH)

if len(args) < 1:
    parser.error("You must specify a VOSpace to list.")

logger.debug("Connecting to vospace using certificate %s" % opt.certfile)

try:
    client = vos.Client(certFile=opt.certfile)
except Exception, e:
    logger.error("Connection failed:  %s" % (str(e)))
    sys.exit(-1)


def size_format(size):
    """Format a size value for listing"""
    if opt.human:
        size_unit = ['B', 'K', 'M', 'G']
        try:
            length = float(size)
            scale = int(math.log(length) / math.log(1024))
            length = "%.0f%s" % (length / (1024.0 ** scale), size_unit[scale])
        except:
            length = str(size)
    else:
        length = str(int(size))
    return "%12s " % length


def date_format(epoch):
    """given a time object return a unix-ls like formatted string"""

    time_tuple = time.localtime(epoch)
    if time.localtime().tm_year != time_tuple.tm_year:
        return time.strftime('%b %d  %Y ', time_tuple)
    return time.strftime('%b %d %H:%S ', time_tuple)

columns = ['permissions']
if opt.long:
    columns.extend(['creator'])
columns.extend(['readGroup', 'writeGroup', 'isLocked', 'size', 'date'])

formats = {'permissions': lambda value: "%-11s" % value,
           'creator': lambda value: " %-20s" % value,
           'readGroup': lambda value: " %-15s" % ("'" + value.replace(vos.CADC_GMS_PREFIX, "") + "'"),
           'writeGroup': lambda value: " %-15s" % ("'" + value.replace(vos.CADC_GMS_PREFIX, "") + "'"),
           'isLocked': lambda value: " %-8s" % ("", "LOCKED")[value == "true"],
           'size': size_format,
           'date': date_format}

for node in args:

    if node[0:4] != "vos:":
        parser.error("Improper vospace specification: %s " % node)
    try:
        logger.debug("getting listing of: %s" % str(node))
        infoList = client.getInfoList(node)
    except IOError as e:
        logger.error("Error getting listing of %s ( %s )" % (node, e.strerror))
        sys.exit(e.errno)
    except Exception as e:
        logger.error("Error getting listing of %s ( %s )" % (node, str(e)))
        sys.exit(-1)

    if sortKey:
        infoList = sorted(infoList, key=lambda name: name[1][sortKey], reverse=not opt.reverse)

    for item in infoList:
        name_string = item[0]
        if opt.long or opt.group:
            for col in columns:
                sys.stdout.write(formats[col](item[1][col]))
            if item[1]["permissions"][0] == 'l':
                name_string = "%s -> %s" % (name_string, item[1]['target'])
        sys.stdout.write("%s " % name_string)
        sys.stdout.write("\n")

sys.exit(0)
