#!/usr/bin/env python2.7
"""Create a directory (ContainerNode) in the VOSpace repositotry"""


import vos
import time
import os, sys, logging
from optparse import OptionParser
from vos import vos, __version__

usage="""
        vrmdir vos:/root/node   -- deletes a container node

Version: %s """ % (__version__.version)



parser=OptionParser(usage)
parser.add_option("-v","--verbose",action="store_true")
parser.add_option("-d","--debug",action="store_true")
parser.add_option("--certfile",help="location of your CADC security certificate file",default=os.path.join(os.getenv("HOME","."),".ssl/cadcproxy.pem"))
parser.add_option("--version", action="store_true", help="VOS Version %s" % (__version__.version))

if len(sys.argv) == 1:
        parser.print_help()
        sys.exit()
        
(opt,args)=parser.parse_args()

if opt.version:
        sys.stdout.write("vrmdir version %s \n\n" % (__version__.version)) 
        sys.exit()

if opt.verbose:
    logging.basicConfig(level=logging.INFO,format="vmkdir: %(message)s")
elif opt.debug:
    logging.basicConfig(level=logging.DEBUG,format="vcp:%(module)s.%(funcName)s %(message)s")
else:
    logging.basicConfig(level=logging.ERROR,format="vcp:%(module)s.%(funcName)s %(message)s")

try:
    client=vos.Client(certFile=opt.certfile)
except Exception as e:
    logging.error("Conneciton failed:  %s" %  (str(e)))
    sys.exit(e.errno)


try:
   for arg in args:
      if arg[0:4]!="vos:":
          logging.error("%s is not a valid VOSpace handle" % (arg))
          sys.exit(-1)
      if client.isdir(arg):
          logging.info("deleting %s" %(arg))
          client.delete(arg)
      elif client.isfile(arg):
          logging.error("%s is a file" % (arg))
          sys.exit(-1)
      else:
          logging.error("%s file not found" % (arg))
          sys.exit(-1)
except Exception as e:
    logging.error("Conneciton failed:  %s" %  (str(e)))
    sys.exit(-1)

